### PR TITLE
Bump `coursier` to 2.1.15 & Scala to 2.13.15

### PR DESCRIPTION
**Pull request by Gedochao**
https://github.com/coursier/coursier/releases/tag/v2.1.15

### CODE REVIEW

**Comment by Gedochao** [comment]
```
Resolution failed for 1 modules:
--------------------------------------------
  io.get-coursier:coursier-cli_2.12:2.1.15 
	not found: /root/.ivy2/local/io.get-coursier/coursier-cli_2.12/2.1.15/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/2.1.15/coursier-cli_2.12-2.1.15.pom
```
🤔

**Comment by tgodzik** [comment]
Ach, we publish only using 2.12, do we actually need to continue publishing the image? Should we not move it to coursier?

**Comment by tgodzik** [comment]
I guess we have two options:
- switch to 2.13 here
- add M1 publish to coursier

@alexarchambault is it time to move arm publishing to coursier?

**Comment by tgodzik** [comment]
We can remove the macos jobs though next https://github.com/coursier/coursier/pull/3148

**Comment by tgodzik** [comment]
> java.lang.UnsupportedClassVersionError: coursier/bootstrap/launcher/Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

We need to switch to JDK 17 (or wait for next release, though it's native image so it's not necessary to publish on JDK 8)

**Comment by tgodzik** [comment]
And here also https://github.com/VirtusLab/coursier-m1/blob/main/.github/scripts/build-linux-aarch64-from-docker.sh#L9

**Review by tgodzik — APPROVED** [review]
Looks good!

**Pull request merged**
